### PR TITLE
Content-Range support

### PR DESCRIPTION
**Pull request by gregkare**
Example, getting the first 65 bytes of an MP4 file:

```
$ curl -H "Range: bytes=0-64" "https://storage.5apps.dev/gregkare/public/shares/200102-1407-Tenac003%231.m4a" -v
*   Trying 192.168.42.23...
* TCP_NODELAY set
* Connected to storage.5apps.dev (192.168.42.23) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=NL; ST=Amsterdam; O=5apps; OU=Internal; CN=5apps Internal
*  start date: Jan  2 18:34:15 2019 GMT
*  expire date: Jan  1 18:34:15 2024 GMT
*  subjectAltName: host "storage.5apps.dev" matched cert's "*.5apps.dev"
*  issuer: C=NL; ST=Amsterdam; O=5apps; OU=Internal; CN=5apps Internal
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7feacd809200)
> GET /gregkare/public/shares/200102-1407-Tenac003%231.m4a HTTP/2
> Host: storage.5apps.dev
> User-Agent: curl/7.54.0
> Accept: */*
> Range: bytes=0-64
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 206
< server: openresty
< date: Thu, 02 Jan 2020 17:25:40 GMT
< content-type: audio/x-m4a; charset=binary
< content-length: 65
< access-control-allow-origin: *
< access-control-allow-methods: GET, PUT, DELETE
< access-control-allow-headers: Authorization, Content-Type, Origin, If-Match, If-None-Match, Range
< access-control-expose-headers: ETag, Content-Length, Content-Range
< accept-ranges: bytes
< cache-control: no-cache
< content-range: bytes 0-64/6616063
< etag: "0450dbd2631e5c38924739b8643d8075"
< last-modified: Thu, 02 Jan 2020 14:07:39 GMT
< strict-transport-security: max-age=15768000; includeSubDomains; preload
<
* Connection #0 to host storage.5apps.dev left intact
 ftypM4A M4A mp42isommoovlmvhdƣƣD
```

New/updated response headers:

```
# Returns a Partial Content status https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206
< HTTP/2 206
# Range
< access-control-allow-headers: Authorization, Content-Type, Origin, If-Match, If-None-Match, Range
# Content-Range
< access-control-expose-headers: ETag, Content-Length, Content-Range
< accept-ranges: bytes
< content-range: bytes 0-64/6616063
```

Do you have any pointer about getting an `<audio>` HTML element to use the `Range` header? So far I could only get it to work using cURL

Refs #82

### CODE REVIEW

**Comment by skddc** [comment]
> Do you have any pointer about getting an `<audio>` HTML element to use the `Range` header? So far I could only get it to work using cURL

That's done automatically by the browser.

**Comment by gregkare** [comment]
Cool, I got it to work in the `<audio>` element in Inspektor, and also by loading the file in a tab in Firefox. Yesterday I was throttling at speeds that were too slow (Regular 3G is good for testing a compressed audio file), so it looked like it wouldn't load anything

**Comment by gregkare** [comment]
Could you take look at the PR and try this in a VM? Thanks

**Comment by skddc** [comment]
I cannot, because our development environment doesn't use a local storage option. My Internet is too slow to actually upload a sufficiently large file for testing.

**Comment by skddc** [comment]
Oh, also LQ gives me 400s in dev. Could it be that I have to renew the auth token somehow?

**Comment by gregkare** [comment]
> Oh, also LQ gives me 400s in dev. Could it be that I have to renew the auth token somehow?

No, it sounds like maybe your lq config.yml file was replaced, did you provision chef again recently?

**Comment by skddc** [comment]
> did you provision chef again recently?

Not that I know of. At least not after it worked last time.

**Comment by gregkare** [comment]
@skddc Does your config.yml include the following under the s3 key? https://sos-ch-dk-2.exo.io/ as the endpoint

The access_key_id and secret_key_id have not changed

**Comment by skddc** [comment]
It does. I'll reload my VM.

**Comment by skddc** [comment]
> I'll reload my VM.

That helped! Still don't have good enough Internet for uploading a test file though.

**Comment by skddc** [comment]
> I'll reload my VM.

That helped! Still don't have good enough Internet for uploading a test file though.

**Comment by skddc** [comment]
It looks like MinIO is very easy to run with just file system as a local S3 storage backend! I'll try that.

**Comment by skddc** [comment]
Yay, I was able to use https://min.io/download to use it as local S3 in the easiest way possible. The partial download works like a charm!

I found some related config issues on the way, which I will fix with a new PR.

**Pull request merged**
