### PR TITLE
WIP: Fix 500 when last-modified missing in Redis

### LINKED ISSUE #135: NoMethodError: undefined method `/' for nil:NilClass
https://sentry.io/organizations/5apps/issues/1426307576/?referrer=github_plugin

```
NoMethodError: undefined method `/' for nil:NilClass
  lib/remote_storage/rest_provider.rb:503:in `block in get_directory_listing_from_redis_via_lua'
    v["Last-Modified"] = Time.at(v["Last-Modified"]/1000).httpdate
  lib/remote_storage/rest_provider.rb:502:in `each'
    items.reject{|k, _| k.end_with? "/"}.each do |_, v|
  lib/remote_storage/rest_provider.rb:502:in `get_directory_listing_from_redis_via_lua'
    items.reject{|k, _| k.end_with? "/"}.each do |_, v|
  lib/remote_storage/rest_provider.rb:102:in `get_directory_listing'
    items = get_directory_listing_from_redis_via_lua(user, directory)
...
(38 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by skddc**
I have trouble running the tests on my machine, so this is just an untested idea for a quick fix for now.

fixes #135

### CODE REVIEW

**Comment by gregkare** [comment]
The change looks good to me, I'm going to write a spec to go with it, because right now the specs are still green with this change

**Comment by gregkare** [comment]
I have added specs in 21a5700

**Comment by skddc** [comment]
So you think it should be a normal case that `last-modified` is missing? I"m not so sure about that.

**Comment by gregkare** [comment]
It's definitely not a normal case, I have checked the code. In the new spec I have manually deleted the `m` key from Redis after a successful request.

You're right, it must be for files that were created before we started storing the date from the S3 response as `Last-Modified` on PUTs

**Comment by gregkare** [comment]
Actually, I can't find a point in time where liquor-cabinet did not store a Last-Modified date. Before d05cd4a it would do a head request on the newly created file, and since that it's using the Date header from the PUT request's response

Almost two years ago we added the Last-Modified to the listings in 60c508f, but the values were always stored in Redis

**Comment by skddc** [comment]
So then it's actually not expected that it would ever be empty. Meaning at least the staging data is corrupt.

**Comment by gregkare** [comment]
I found a file on staging that has a Last-Modified stored in Redis that looks like this: "2018-04-11 15:09:02 +0000". When turned into an integer by the `tonumber` lua function it turns into nil. I'm now figuring out how this has been saved as a string instead of a timestamp.

**Comment by skddc** [comment]
Closing this one, because it is a valid exception that should raise in the future in case someone's data is inconsistent.

**Pull request closed without merging**
